config/routes.rb
Rails.application.routes.draw do
  get 'profile/index'
  resources :cats
  root 'pages#home'
  get 'pages/home'
  devise_for :users
  get '/profile', to: 'profile#index'
  get '/admin', to: 'admin#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cat.rb
class Cat < ApplicationRecord
  belongs_to :user
  has_many_attached :images

  has_many_attached :images do |image|
    # image.variant :basic, resize_to_limit: [150, 150]
    image.variant :basic, resize_to_fill: [220, nil]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  enum role: [:user, :moderator, :admin]
  after_initialize :set_default_role, :if => :new_record?

  has_one_attached :avatar do |attachable|
    attachable.variant :thumb, resize_to_fill: [35, 35]
  end
  
  has_many :cats, dependent: :destroy

  def set_default_role
    self.role ||= :user
  end 
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
before_action :admin_filter
        

def index
end



private

def admin_filter
    if is_admin?
        flash[:notice] = 'Admin Mode Activated'
    else
        flash[:alert] = 'No chiki chiki please...'
        redirect_to :root
    end
end 
            
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    def is_admin?
        current_user && current_user.admin?
    end


    
    protected
    
      def after_sign_in_path_for(resource)
        if(is_admin?) then
          admin_path
        else
          cats_path
        end
      end

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar])
    end

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index show ]

  # GET /cats or /cats.json
  def index
    @cats = Cat.all
  end

  # GET /cats/1 or /cats/1.json
  def show
  end

  # GET /cats/new
  def new
    @cat = Cat.new(user_id: current_user.id)
  end

  # GET /cats/1/edit
  def edit
    @images_field_disabled = true
  end

  def create
    @cat = Cat.new(cat_params)
    @cat.user_id = current_user.id
    respond_to do |format|
      if @cat.save
        format.html { redirect_to cat_url(@cat), notice: "Cat was successfully created." } 
      else
        format.html { render :new, status: :unprocessable_entity } 
      end
    end
  end

  def update
    respond_to do |format|
      if @cat.update(cat_params)
        format.turbo_stream { redirect_to profile_index_path }
        format.html { redirect_to cat_url(@cat), notice: "Cat was successfully updated." } 
      else
        format.html { render :edit, status: :unprocessable_entity } 
      end
    end
  end

  def destroy
    @cat.destroy

    respond_to do |format|
      format.html { redirect_to cats_url, notice: "Cat was successfully destroyed." } 
    end
  end

  private
    def set_cat
      @cat = Cat.find(params[:id])
    end
 
    def cat_params
      params.require(:cat).permit(:name, :user_id, images: [])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController

  before_action :authenticate_user!, only: %i[ index show ]
  def index
    @cats = current_user.cats
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_admin?
    current_user && current_user.admin?
  end

  def avatar
    if current_user.avatar.present?
      image_tag current_user.avatar.variant(:thumb), class: 'header_avatar rounded-full inline'
    else
      image_tag 'default_avatar.jpg', class: 'header_avatar header_default_avatar rounded-full inline'
    end
  end

  def avatar_link
    link_to profile_index_path, class: 'user_profile_link' do
      avatar
    end
  end
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/admin/index.html.erb
<%# Side Panel %>
<% content_for :admin do %>
<div class="bg-violet-800 fixed top-14 bottom-0 left-0 w-52">

  <div class="bg-violet-700 p-2 text-violet-200"><%= current_user.role.capitalize %></div>
  <div class="p-2">
    <div class="p-2">

      Users
    </div>
    <div class="p-2">Cats</div>
    <div class="p-2">Stats</div>
    <div class="p-2">Settings</div>
  </div>

</div>

 <%# Main Admin Panel %>
  <div id="admin-panel" class="bg-slate-100 ml-52 pt-14">
    <div class="p-2">
    <h5>Admin mode active || <%= current_user.role %></h5>
    <p>User Count: <%= User.count %></p>
    <div class="">
      <div class="flex">
        <div class="basis-1/4">Email</div>
        <div class="basis-1/4"></div>
        <div class="basis-1/4"></div>
        <div class="basis-1/4">Avatar</div>
      </div>
      <% User.all.each do |user|%>
        <div class="flex my-1">
          <div class="basis-1/4"><%= user.email %></div>
          <div class="basis-1/4"><% user.cats.count %></div>
          <div class="basis-1/4"></div>
          <div class="basis-1/4">
            <% if (user.avatar).present? %>
              <%= image_tag user.avatar.variant(:thumb), :class=>"rounded-lg" %>
            <% end %>
          </div>
        </div>
      <% end %>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      <br>
      </div>
    </div>
  </div>
  
<% end %>

app/views/cats/_cat.html.erb
<div id="<%= dom_id cat %>" class="w-96 mx-auto">
    <% if cat.images.attached? %>
      <% cat.images.each_with_index  do |image, i|%>
        <% if(i==0)then %>
          <%= image_tag image.variant(:basic), :class=>"rounded-xl mx-auto" %>
        <%end%>
      <% end %>
    <% end %>
    <h3 class="text-xl p-3 text-center">
      <%= cat.name %>
    </h3>
</div>

app/views/cats/_form.html.erb
  <div class="cat-form">
    <%= form_with(model: cat ) do |form| %>
      <% if cat.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(cat.errors.count, "error") %> prohibited this cat from being saved:</h2>

          <ul>
            <% cat.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
  
        <%= form.label :name %>
        <%= form.text_field :name, class: 'w-full px-4 py-2 rounded-lg border border-gray-300 outline-none focus:border-gray-400' %>
        <%= form.file_field :images, multiple: true unless @images_field_disabled %>
        <%= form.submit :class => 'btn' %>
 
    <% end %> 
  </div>

app/views/cats/edit.html.erb
<%= turbo_frame_tag @cat do %>
  <%= turbo_frame_tag 'modal' do %>
    <%= render "form", cat: @cat %> 
  <% end %>
  <%= link_to profile_index_path do %>
    <%= image_tag 'back', class: "action_btn inline-block", alt: 'Whatever..' %>
  <% end %>
<% end %>

app/views/cats/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Cats</h1>
<div id="cats" class="">
  <% @cats.each do |cat| %>
    <%= render cat %>
  <% end %>
</div>
<% if current_user then %>
  <%= link_to "New cat", new_cat_path %>
<% end %>

app/views/cats/new.html.erb
<h1>New cat</h1>
<%= turbo_frame_tag 'modal', class: 'relative' do %>
  <%= tag.div data: { controller: "turbo-modal" }, class: "p-8"  do %>
    <%= render "form", cat: @cat %>
    <%= button_tag "x", data: { action: "turbo-modal#hideModal" }, type: "button", class: "absolute top-2 right-2 py-3 px-5 " %>
  <% end %>
  
<% end %>

<br>

<div>
  <%= link_to "Back to cats", cats_path %>
</div>

app/views/cats/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cat %>

<div>
  <%= link_to "Edit this cat", edit_cat_path(@cat) %> |
  <%= link_to "Back to cats", cats_path %>

  <%= button_to "Destroy this cat", @cat, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coolcat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Flex:opsz,wght@8..144,100;8..144,200;8..144,300;8..144,400;8..144,500;8..144,600;8..144,700;8..144,800;8..144,900;8..144,1000&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%= turbo_frame_tag 'modal', class:"bg-white drop-shadow" %>
    <%= render 'partials/header' %>
    <%= render 'shared/flash' %>
      <%= yield :admin %>
    <div class="container pt-14">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<% if current_user %>
  <% if current_user.cats.count==0 %>
    <%= link_to 'Add your first kitty', new_cat_path %>
  <% else %>
  <div class="mt-2">
    <% current_user.cats.each do |cat| %>
      <%= render cat %>
    <% end %>
  </div>
  <% end %>
<% else %>
  <div class="flex justify-center gap-10 mt-24">
    <%= link_to 'Log in', new_user_session_path, class: "btn" %>
    <%= link_to 'Sign up', new_user_registration_path, class: "btn" %>
  </div>
<% end %>

app/views/partials/_admin_panel.html.erb
<div id="admin-panel">
  <h5 class="bg-slate-500">Admin mode active || <%= current_user.role %></h5>
  <p>User Count: <%= User.count %></p>
  <div class="bg-slate-100">
    <% User.all.each do |user|%>
      <%= user.email %>
      <% if (user.avatar).present? %>
        <%= image_tag user.avatar.variant(:thumb) %>
      <% end %>
      <br>
    <% end %>
    <br>
  </div>
</div>

app/views/partials/_header.html.erb
<div class="fixed left-0 right-0 drop-shadow-sm bg-white border-bottom border-2 border-gray-300 h-14 py-1 px-4 flex gap-1" id="header_partial">
  <%= link_to :root do %>
    <h1>CoolCat</h1>
  <% end %>
  <div class="ml-auto flex gap-2 items-center">
    <% if current_user %>
      <div>
      <%= avatar_link %>
      </div>
        <div>
          <div></div><%= current_user.role %> | <span id="user_email"><%= current_user.email %></span>
          <div><%= link_to 'Sign out', destroy_user_session_path, 'data-turbo-method': :delete  %></div>
        </div>
      </div>
    <% else %>
      <%= link_to 'Sign up', new_user_registration_path %> || 
      <%= link_to 'Login', new_user_session_path %>
    <% end %>
  </div>
</div>

app/views/shared/_flash.html.erb
<% if notice.present? %>
    <div class="fixed right-0 top-14">
        <div class="p-2 bg-blue-200 rounded-lg"><%= notice %></div>
    </div>
<% end %>

<% if  alert.present? %>
    <div class="fixed right-0 top-14">
        <div class="p-2 bg-red-200"><%= alert %></div>
    </div>
<% end %>